#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================


# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "SpaceVim"
    colorscheme_bg = "dark"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true 
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    enable_neomake = 0
    lint_on_the_fly = 1
    bootstrap_before = "myspacevim#before"
    bootstrap_after= "myspacevim#after"
#disabled_plugins=["CompleteParameter.vim"]
# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  autocomplete_method = 'asyncomplete'
  auto-completion-enable-snippets-in-popup = 0
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"
  auto-completion-complete-with-key-sequence = "nil"
  auto-completion-complete-with-key-sequence-delay = 0.1

[[layers]]
  name = "colorscheme"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'lsp'
  filetypes = [
    'python',
    'c',
    'cpp',
    'css',
    'html',
    'javascript',
    'sh',
    'php'
  ] 
  [layers.override_cmd]
    php = ["php", "~/vendor/felixfbecker/language-server/bin/php-language-server.php"]

[[layers]]
  name = 'edit'

[[layers]]
  name = 'sudo'

[[layers]]
  name = 'git'

[[layers]]
  name = 'ctrlp'

[[layers]]
  name = 'lang#php'

[[layers]]
  name = 'lang#c'

[[layers]]
  name = 'lang#sh'

[[layers]]
  name = 'lang#python'
  format-on-save = 0

[[layers]]
  name = 'lang#javascript'
