#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
 autocomplete_method = "asyncomplete"

[[layers]]
  name = "format"

[[layers]]
  name = 'lang#c'
  enable_clang_syntax_highlight = true

[[layers]]
  name = 'lang#python'

[[layers]]
  name = 'lang#rust'

[[layers]]
  name = 'lang#php'

[[layers]]
  name = 'lang#sql'

[[layers]]
  name = 'lang#sh'

[[layers]]
  name = 'lang#javascript'

[[layers]]
  name = "git"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "lsp"
  filetypes = [
    "rust",
    "javascript",
    "sh",
    "python",
    "cpp",
    "c"
  ]

[[layers]]
  name = "ctrlp"

[[layers]]
  name = "format"

[options]
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '!node_packages/']
    project_rooter_outermost = false
